name: Fuzzing

on: [push, pull_request]

jobs:
  fuzz:
    name: Run Fuzzing
    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - uses: jidicula/go-fuzz-action@v1.2.0
        with:
          go-version: '1.20'
          fuzz-time: 15m
