name: Fuzzing

on: [push, pull_request]

jobs:
  fuzz:
    name: Run Fuzzing
    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:
      - uses: jidicula/go-fuzz-action@891563262ea6c61284a881290a84f8f709fca6df
        with:
          go-version: '1.22'
          fuzz-time: 5m
